// import { Metadata } from "next"
// import { urlFor } from "@/sanity/lib/image"
// import { sanityFetch } from '@/sanity/lib/live'
// import { SITE_SETTINGS_QUERY } from '@/sanity/queries'

// const defaultMetadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   image: "/card.jpg",
//   url: "https://www.vercel.com/",
//   twitterHandle: "@vercel"
// }

// export async function createMetadata(pageMetadata?: {
//   title?: string | null;
//   description?: string | null;
//   image?: string | null;
// }): Promise<Metadata> {
//   const { data: seoSettings } = await sanityFetch({ 
//     query: SITE_SETTINGS_QUERY 
//   });
  
//   // Base metadata using settings with fallbacks
//   const baseMetadata: Metadata = {
//     metadataBase: new URL(defaultMetadata.url),
//     title: seoSettings?.seo?.metaTitle || defaultMetadata.title,
//     description: seoSettings?.seo?.metaDescription || defaultMetadata.description,
//     icons: { 
//       icon: seoSettings?.seo?.metaImage ? urlFor(seoSettings.seo.metaImage).url() : '/favicon.ico' 
//     },
//     openGraph: {
//       title: seoSettings?.seo?.metaTitle || defaultMetadata.title,
//       description: seoSettings?.seo?.metaDescription || defaultMetadata.description,
//       url: defaultMetadata.url,
//       siteName: seoSettings?.companyName || "Simbe Robotics",
//       images: [{
//         url: seoSettings?.seo?.metaImage ? urlFor(seoSettings.seo.metaImage).url() : defaultMetadata.image,
//         width: 1200,
//         height: 600,
//       }],
//     },
//     twitter: {
//       card: "summary_large_image",
//       title: seoSettings?.seo?.metaTitle || defaultMetadata.title,
//       description: seoSettings?.seo?.metaDescription || defaultMetadata.description,
//       creator: defaultMetadata.twitterHandle,
//       images: [{
//         url: seoSettings?.seo?.metaImage ? urlFor(seoSettings.seo.metaImage).url() : defaultMetadata.image,
//         width: 1200,
//         height: 600,
//       }],
//     },
//   }

//   // If no page metadata, return base metadata
//   if (!pageMetadata) return baseMetadata

//   // Merge page metadata with base metadata
//   return {
//     ...baseMetadata,
//     title: pageMetadata.title || baseMetadata.title,
//     description: pageMetadata.description || baseMetadata.description,
//     openGraph: {
//       ...baseMetadata.openGraph,
//       title: pageMetadata.title || baseMetadata.openGraph?.title,
//       description: pageMetadata.description || baseMetadata.openGraph?.description,
//       images: pageMetadata.image ? [{
//         url: pageMetadata.image,
//         width: 1200,
//         height: 600,
//       }] : baseMetadata.openGraph?.images,
//     },
//     twitter: {
//       ...baseMetadata.twitter,
//       title: pageMetadata.title || baseMetadata.twitter?.title,
//       description: pageMetadata.description || baseMetadata.twitter?.description,
//       images: pageMetadata.image ? [{
//         url: pageMetadata.image,
//         width: 1200,
//         height: 600,
//       }] : baseMetadata.twitter?.images,
//     },
//   }
// }