/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type PageBuilder = Array<
  | ({
      _key: string
    } & Hero)
  | ({
      _key: string
    } & Features)
  | ({
      _key: string
    } & ProductGrid)
  | ({
      _key: string
    } & ProductCarousel)
  | ({
      _key: string
    } & FeaturedItems)
  | ({
      _key: string
    } & Newsletter)
  | ({
      _key: string
    } & Testimonials)
  | Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'large' | 'small' | 'lead'
      listItem?: 'bullet' | 'number' | 'check'
      markDefs?: Array<{
        href?: string
        target?: '_self' | '_blank'
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
>

export type ProductDetails = {
  _type: 'productDetails'
  product?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'product'
  }
  layout?: 'standard' | 'gallery' | 'sticky' | 'fullWidth'
  galleryLayout?: 'grid' | 'thumbnails' | 'stack'
  showThumbnails?: boolean
  showZoom?: boolean
  showQuantity?: boolean
  showVariantSelector?: boolean
  showPrice?: boolean
  showCompare?: boolean
  showShare?: boolean
  showStock?: boolean
  showSKU?: boolean
  showVendor?: boolean
  showTags?: boolean
  cta?: {
    text?: string
    url?: string
    internalPage?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
    style?: 'primary' | 'secondary' | 'ghost' | 'text'
    size?: 'default' | 'small' | 'large'
  }
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
}

export type Testimonials = {
  _type: 'testimonials'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'large' | 'small' | 'lead'
    listItem?: 'bullet' | 'number' | 'check'
    markDefs?: Array<{
      href?: string
      target?: '_self' | '_blank'
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  testimonials?: Array<{
    quote?: string
    author?: {
      name?: string
      title?: string
      image?: {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
    }
    rating?: 1 | 2 | 3 | 4 | 5
    _key: string
  }>
  cta?: {
    text?: string
    url?: string
    internalPage?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
    style?: 'primary' | 'secondary' | 'ghost' | 'text'
    size?: 'default' | 'small' | 'large'
  }
  layout?: 'grid' | 'carousel' | 'stack'
  columns?: 1 | 2 | 3
  background?: 'none' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
  showArrows?: boolean
  showDots?: boolean
  autoplay?: boolean
}

export type Newsletter = {
  _type: 'newsletter'
  layout?: 'standard' | 'compact' | 'fullWidth' | 'card'
  showTitle?: boolean
  title?: string
  showDescription?: boolean
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'large' | 'small' | 'lead'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      target?: '_self' | '_blank'
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  showMarketingPreferences?: boolean
  marketingPreferences?: Array<{
    label?: string
    value?: string
    checked?: boolean
    _key: string
  }>
  showPrivacyPolicy?: boolean
  privacyPolicyText?: string
  privacyPolicyLink?: string
  showSuccessMessage?: boolean
  successMessage?: string
  showErrorMessage?: boolean
  errorMessage?: string
  showPlaceholder?: boolean
  placeholder?: string
  showButton?: boolean
  buttonText?: string
  buttonStyle?: 'primary' | 'secondary' | 'outline' | 'ghost'
  showIcon?: boolean
  icon?: 'envelope' | 'bell' | 'paper-plane' | 'send'
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
}

export type FeaturedItems = {
  _type: 'featuredItems'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'large' | 'small' | 'lead'
    listItem?: 'bullet' | 'number' | 'check'
    markDefs?: Array<{
      href?: string
      target?: '_self' | '_blank'
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  items?: Array<{
    title?: string
    description?: string
    image?: ImageComponent
    item?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'collection'
        }
    ctaText?: string
    _key: string
  }>
  defaultCtaText?: string
  layout?: 'grid' | 'carousel' | 'masonry' | 'list'
  columns?: 2 | 3 | 4
  itemLayout?: 'card' | 'compact' | 'minimal'
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
  showArrows?: boolean
  showDots?: boolean
  autoplay?: boolean
  itemsPerView?: 2 | 3 | 4
}

export type Hero = {
  _type: 'hero'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'large' | 'small' | 'lead'
    listItem?: 'bullet' | 'number' | 'check'
    markDefs?: Array<{
      href?: string
      target?: '_self' | '_blank'
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  image?: ImageComponent
  overlay?: Array<string>
  ctas?: Array<{
    text?: string
    url?: string
    internalPage?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
    style?: 'primary' | 'secondary' | 'ghost' | 'text'
    size?: 'default' | 'small' | 'large'
    _key: string
  }>
  layout?: 'left' | 'center' | 'right'
  height?: 'small' | 'medium' | 'large' | 'fullScreen'
}

export type Features = {
  _type: 'features'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'large' | 'small' | 'lead'
    listItem?: 'bullet' | 'number' | 'check'
    markDefs?: Array<{
      href?: string
      target?: '_self' | '_blank'
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  features?: Array<{
    title?: string
    description?: string
    icon?: 'none' | 'check' | 'star' | 'heart' | 'shield' | 'lightning' | 'rocket' | 'gear'
    image?: ImageComponent
    _key: string
  }>
  cta?: {
    text?: string
    url?: string
    internalPage?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
    style?: 'primary' | 'secondary' | 'ghost' | 'text'
    size?: 'default' | 'small' | 'large'
  }
  layout?: 'grid' | 'list' | 'cards'
  columns?: 2 | 3 | 4
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
}

export type CollectionNavigation = {
  _type: 'collectionNavigation'
  layout?: 'sidebar' | 'topBar' | 'drawer'
  showCategoryTree?: boolean
  maxDepth?: 1 | 2 | 3
  showProductCount?: boolean
  showFilters?: boolean
  filterOptions?: Array<{
    title?: string
    type?: 'price' | 'vendor' | 'productType' | 'tags' | 'availability' | 'rating'
    defaultValue?: string
    _key: string
  }>
  showSortOptions?: boolean
  sortOptions?: Array<{
    label?: string
    value?: string
    _key: string
  }>
  defaultSort?: string
  showActiveFilters?: boolean
  showClearFilters?: boolean
  showMobileFilters?: boolean
  mobileFilterPosition?: 'drawer' | 'bottomSheet' | 'fullScreen'
  showPagination?: boolean
  productsPerPage?: 12 | 24 | 36 | 48
  showResultsCount?: boolean
  showBreadcrumbs?: boolean
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
}

export type ProductGrid = {
  _type: 'productGrid'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'large' | 'small' | 'lead'
    listItem?: 'bullet' | 'number' | 'check'
    markDefs?: Array<{
      href?: string
      target?: '_self' | '_blank'
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  collection?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'collection'
  }
  products?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'product'
  }>
  layout?: 'grid' | 'list' | 'masonry'
  columns?: 2 | 3 | 4
  showFilters?: boolean
  filterOptions?: Array<{
    title?: string
    type?: 'price' | 'vendor' | 'productType' | 'tags' | 'availability'
    defaultValue?: string
    _key: string
  }>
  sortOptions?: Array<{
    label?: string
    value?: string
    _key: string
  }>
  defaultSort?: string
  productsPerPage?: 12 | 24 | 36 | 48
  showQuickView?: boolean
  showAddToCart?: boolean
  showPrice?: boolean
  showCompare?: boolean
  cta?: {
    text?: string
    url?: string
    internalPage?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
    style?: 'primary' | 'secondary' | 'ghost' | 'text'
    size?: 'default' | 'small' | 'large'
  }
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
}

export type ProductCarousel = {
  _type: 'productCarousel'
  content?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'large' | 'small' | 'lead'
    listItem?: 'bullet' | 'number' | 'check'
    markDefs?: Array<{
      href?: string
      target?: '_self' | '_blank'
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  products?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'product'
  }>
  productsPerView?: 2 | 3 | 4
  showArrows?: boolean
  showDots?: boolean
  autoplay?: boolean
  autoplaySpeed?: number
  cta?: ButtonLink
}

export type SimpleBlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'large' | 'small' | 'lead'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    target?: '_self' | '_blank'
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type EditorialBlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?:
        | 'normal'
        | 'h1'
        | 'h2'
        | 'h3'
        | 'h4'
        | 'h5'
        | 'h6'
        | 'blockquote'
        | 'pullQuote'
        | 'caption'
        | 'captionLarge'
        | 'captionSmall'
        | 'large'
        | 'small'
        | 'code'
        | 'footnote'
      listItem?: 'bullet' | 'number' | 'check'
      markDefs?: Array<
        | {
            href?: string
            target?: '_self' | '_blank'
            _type: 'link'
            _key: string
          }
        | never
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
      size?: 'small' | 'medium' | 'large' | 'fullWidth'
      alignment?: 'left' | 'center' | 'right'
      _type: 'image'
      _key: string
    }
  | {
      content?: Array<{
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }>
      type?: 'info' | 'warning' | 'success' | 'error' | 'tip'
      _type: 'callout'
      _key: string
    }
  | {
      code?: string
      language?: 'javascript' | 'typescript' | 'html' | 'css' | 'json' | 'markdown'
      _type: 'codeBlock'
      _key: string
    }
>

export type SimpleLink = {
  _type: 'simpleLink'
  text?: string
  url?: string
  internalPage?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'blogPost'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'event'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'product'
      }
}

export type ButtonLink = {
  _type: 'buttonLink'
  text?: string
  url?: string
  internalPage?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'blogPost'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'event'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'product'
      }
  style?: 'primary' | 'secondary' | 'ghost' | 'text'
  size?: 'default' | 'small' | 'large'
}

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'large' | 'small' | 'lead'
  listItem?: 'bullet' | 'number' | 'check'
  markDefs?: Array<{
    href?: string
    target?: '_self' | '_blank'
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type ContactForm = {
  _id: string
  _type: 'contactForm'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  klaviyoListId?: string
  fields?: Array<{
    name?: string
    label?: string
    type?: 'text' | 'email' | 'phone' | 'textarea' | 'select'
    placeholder?: string
    required?: boolean
    options?: Array<string>
    validation?: {
      pattern?: string
      message?: string
    }
    _key: string
  }>
  successMessage?: string
  errorMessage?: string
}

export type Faq = {
  _id: string
  _type: 'faq'
  _createdAt: string
  _updatedAt: string
  _rev: string
  question?: string
  answer?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  order?: number
  category?: string
}

export type Blog = {
  _id: string
  _type: 'blog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  content?: BlockContent
  layout?: 'grid' | 'list' | 'masonry'
  columns?: 2 | 3 | 4
  showCategories?: boolean
  showTags?: boolean
  showAuthor?: boolean
  showDate?: boolean
  showExcerpt?: boolean
  postsPerPage?: 6 | 9 | 12 | 15
  defaultSort?: 'latest' | 'featured' | 'popular'
  seo?: {
    title?: string
    description?: string
    image?: ImageComponent
  }
}

export type Shop = {
  _id: string
  _type: 'shop'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  content?: BlockContent
  layout?: 'grid' | 'list' | 'masonry'
  columns?: 2 | 3 | 4
  showFilters?: boolean
  showSort?: boolean
  showPagination?: boolean
  productsPerPage?: 12 | 24 | 36 | 48
  defaultSort?: 'featured' | 'best-selling' | 'price-asc' | 'price-desc' | 'newest'
  seo?: {
    title?: string
    description?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type Events = {
  _id: string
  _type: 'events'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  startDate?: string
  endDate?: string
  location?: string
  image?: ImageComponent
  relatedProducts?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'product'
  }>
  capacity?: number
  price?: number
  isPublished?: boolean
}

export type Search = {
  _id: string
  _type: 'search'
  _createdAt: string
  _updatedAt: string
  _rev: string
  layout?: 'fullPage' | 'drawer' | 'modal'
  searchPlaceholder?: string
  showSearchIcon?: boolean
  showClearButton?: boolean
  showFilters?: boolean
  filterOptions?: Array<{
    title?: string
    type?: 'price' | 'vendor' | 'productType' | 'tags' | 'availability' | 'rating'
    defaultValue?: string
    _key: string
  }>
  showSortOptions?: boolean
  sortOptions?: Array<{
    label?: string
    value?: string
    _key: string
  }>
  defaultSort?: string
  showResultsCount?: boolean
  showPagination?: boolean
  productsPerPage?: 12 | 24 | 36 | 48
  showSuggestions?: boolean
  suggestionTypes?: Array<'products' | 'collections' | 'articles' | 'pages'>
  showRecentSearches?: boolean
  maxRecentSearches?: 3 | 5 | 10
  showPopularSearches?: boolean
  popularSearches?: Array<string>
  noResultsMessage?: BlockContent
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
}

export type Checkout = {
  _id: string
  _type: 'checkout'
  _createdAt: string
  _updatedAt: string
  _rev: string
  layout?: 'standard' | 'split' | 'compact'
  steps?: Array<{
    title?: string
    description?: string
    icon?: 'user' | 'location' | 'credit-card' | 'check'
    _key: string
  }>
  showOrderSummary?: boolean
  showShippingOptions?: boolean
  showPaymentMethods?: boolean
  paymentMethods?: Array<{
    title?: string
    value?: string
    icon?: 'credit-card' | 'paypal' | 'apple-pay' | 'google-pay'
    enabled?: boolean
    _key: string
  }>
  showAddressForm?: boolean
  showGiftOptions?: boolean
  showOrderNotes?: boolean
  showDiscountCode?: boolean
  showSaveAddress?: boolean
  showTerms?: boolean
  termsText?: string
  termsLink?: string
  showPrivacyPolicy?: boolean
  privacyPolicyText?: string
  privacyPolicyLink?: string
  showOrderConfirmation?: boolean
  orderConfirmationText?: string
  showOrderNumber?: boolean
  showOrderDetails?: boolean
  showContinueShopping?: boolean
  continueShoppingButton?: {
    text?: string
    url?: string
    internalPage?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
    style?: 'primary' | 'secondary' | 'ghost' | 'text'
    size?: 'default' | 'small' | 'large'
  }
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
}

export type Cart = {
  _id: string
  _type: 'cart'
  _createdAt: string
  _updatedAt: string
  _rev: string
  layout?: 'drawer' | 'page' | 'sidebar'
  showProductImage?: boolean
  showProductTitle?: boolean
  showProductPrice?: boolean
  showQuantity?: boolean
  showVariant?: boolean
  showSubtotal?: boolean
  showTax?: boolean
  showShipping?: boolean
  showTotal?: boolean
  showDiscount?: boolean
  showPromoCode?: boolean
  showCheckoutButton?: boolean
  showContinueShopping?: boolean
  showEmptyCartMessage?: boolean
  emptyCartMessage?: BlockContent
  showCartCount?: boolean
  cartCountPosition?: 'topRight' | 'topLeft' | 'bottomRight' | 'bottomLeft'
  showCartIcon?: boolean
  cartIconStyle?: 'cart' | 'bag' | 'basket'
  checkoutButton?: {
    text?: string
    url?: string
    internalPage?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
    style?: 'primary' | 'secondary' | 'ghost' | 'text'
    size?: 'default' | 'small' | 'large'
  }
  continueShoppingButton?: {
    text?: string
    url?: string
    internalPage?:
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'page'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'blogPost'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'event'
        }
      | {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'product'
        }
    style?: 'primary' | 'secondary' | 'ghost' | 'text'
    size?: 'default' | 'small' | 'large'
  }
  background?: 'transparent' | 'lightGray' | 'darkGray' | 'primary' | 'secondary'
}

export type ProductVariant = {
  _id: string
  _type: 'productVariant'
  _createdAt: string
  _updatedAt: string
  _rev: string
  store?: {
    title?: string
    status?: string
    sku?: string
    price?: number
    compareAtPrice?: number
    availableForSale?: boolean
    isDeleted?: boolean
    id?: number
    productId?: number
    gid?: string
    productGid?: string
    inventory?: {
      isAvailable?: boolean
      management?: string
      policy?: string
    }
    createdAt?: string
    option1?: string
    option2?: string
    option3?: string
  }
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  companyName?: string
  homePage?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  header?: {
    logo?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    mainMenu?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'menu'
    }
    headerButtons?: Array<{
      text?: string
      url?: string
      internalPage?:
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'page'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'blogPost'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'event'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'product'
          }
      style?: 'primary' | 'secondary' | 'ghost' | 'text'
      size?: 'default' | 'small' | 'large'
      _key: string
    }>
  }
  footer?: {
    logo?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    logoCaption?: string
    footerMenu?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'menu'
    }
    newsletter?: {
      title?: string
      description?: string
      klaviyoListId?: string
    }
    footerButtons?: Array<{
      text?: string
      url?: string
      internalPage?:
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'page'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'blogPost'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'event'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'product'
          }
      style?: 'primary' | 'secondary' | 'ghost' | 'text'
      size?: 'default' | 'small' | 'large'
      _key: string
    }>
    footerText?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  defaultSeo?: {
    metaTitle?: string
    metaDescription?: string
    metaImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
  socialMedia?: {
    facebook?: string
    instagram?: string
    twitter?: string
    linkedin?: string
  }
}

export type Menu = {
  _id: string
  _type: 'menu'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  location?: 'header' | 'footer'
  items?: Array<{
    title?: string
    link?: string
    isMegaMenu?: boolean
    megaMenuContent?: {
      columns?: Array<{
        title?: string
        links?: Array<{
          title?: string
          link?: string
          _key: string
        }>
        featuredImage?: ImageComponent
        featuredText?: string
        _key: string
      }>
      featuredProduct?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'product'
      }
      promotion?: {
        title?: string
        description?: string
        image?: {
          asset?: {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
          }
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        link?: string
      }
    }
    subItems?: Array<{
      title?: string
      link?: string
      _key: string
    }>
    _key: string
  }>
}

export type Product = {
  _id: string
  _type: 'product'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  content?: SimpleBlockContent
  images?: Array<
    {
      _key: string
    } & ImageComponent
  >
  productDetails?: Array<{
    title?: string
    text?: SimpleBlockContent
    _key: string
  }>
  pageBuilder?: PageBuilder
  seo?: {
    title?: string
    description?: string
    image?: ImageComponent
  }
  store?: {
    title?: string
    slug?: Slug
    descriptionHtml?: string
    previewImageUrl?: string
    status?: string
    priceRange?: {
      minVariantPrice?: number
      maxVariantPrice?: number
    }
    tags?: Array<{
      name?: string
      tags?: Array<string>
      _type: 'option'
      _key: string
    }>
    variants?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'productVariant'
    }>
    options?: Array<{
      name?: string
      values?: Array<string>
      _type: 'option'
      _key: string
    }>
    productType?: string
    vendor?: string
    id?: number
    gid?: string
    createdAt?: string
    isDeleted?: boolean
  }
}

export type Collection = {
  _id: string
  _type: 'collection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  image?: ImageComponent
  products?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'product'
  }>
  seo?: {
    title?: string
    description?: string
    image?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
  store?: {
    title?: string
    slug?: Slug
    descriptionHtml?: string
    sortOrder?: string
    gid?: string
    createdAt?: string
    id?: number
    isDeleted?: boolean
  }
}

export type BlogPost = {
  _id: string
  _type: 'blogPost'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'team'
  }
  mainImage?: ImageComponent
  categories?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'category'
  }>
  excerpt?: string
  body?: EditorialBlockContent
  relatedProducts?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'product'
  }>
  seo?: {
    metaTitle?: string
    metaDescription?: string
    metaImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  content?: BlockContent
  layout?: 'grid' | 'list' | 'calendar'
  columns?: 2 | 3 | 4
  showCategories?: boolean
  showTags?: boolean
  showDate?: boolean
  showLocation?: boolean
  showPrice?: boolean
  showCapacity?: boolean
  eventsPerPage?: 6 | 9 | 12 | 15
  defaultSort?: 'upcoming' | 'past' | 'featured'
  seo?: {
    title?: string
    description?: string
    image?: ImageComponent
  }
}

export type Team = {
  _id: string
  _type: 'team'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  role?: string
  description?: BlockContent
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  socialLinks?: {
    linkedin?: string
    twitter?: string
    github?: string
  }
}

export type ImageComponent = {
  _type: 'imageComponent'
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    priority?: boolean
    caption?: string
    _type: 'image'
  }
  aspectRatio?: 'auto' | '1:1' | '4:5' | '3:4' | '5:4'
  objectFit?: 'cover' | 'contain' | 'fill'
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  seo?: {
    metaTitle?: string
    metaDescription?: string
    metaImage?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | PageBuilder
  | ProductDetails
  | Testimonials
  | Newsletter
  | FeaturedItems
  | Hero
  | Features
  | CollectionNavigation
  | ProductGrid
  | ProductCarousel
  | SimpleBlockContent
  | EditorialBlockContent
  | SimpleLink
  | ButtonLink
  | BlockContent
  | ContactForm
  | Faq
  | Blog
  | Shop
  | Events
  | Search
  | Checkout
  | Cart
  | ProductVariant
  | Category
  | SiteSettings
  | Menu
  | Product
  | Collection
  | BlogPost
  | Event
  | Team
  | ImageComponent
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata
  | MediaTag
  | Slug
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/queries/index.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "home"][0]{    _id,    _type,    overview,    showcaseProjects[]{      _key,      ...@->{        _id,        _type,        coverImage,        overview,        "slug": slug.current,        tags,        title,      }    },    title,  }
export type HOME_PAGE_QUERYResult = null
// Variable: ALL_PRODUCTS_QUERY
// Query: *[_type == "product"] {    _id,    _type,    title,    images[]{   asset->{    _id,    _type,    url,    metadata {      lqip,      dimensions {        width,        height      },      palette {        dominant {          background,          foreground,          population,          title        }      }    }  },  hotspot {    x,    y,    height,    width  },  crop {    top,    bottom,    left,    right  },  alt,  priority,  caption,  _type,  aspectRatio,  objectFit },    "slug": store.slug.current,    store{      title,      "slug": slug.current,      previewImageUrl,      gid,      status,      priceRange{        minVariantPrice,        maxVariantPrice      }    },  }
export type ALL_PRODUCTS_QUERYResult = Array<{
  _id: string
  _type: 'product'
  title: string | null
  images: Array<{
    asset: null
    hotspot: null
    crop: null
    alt: null
    priority: null
    caption: null
    _type: 'imageComponent'
    aspectRatio: '1:1' | '3:4' | '4:5' | '5:4' | 'auto' | null
    objectFit: 'contain' | 'cover' | 'fill' | null
  }> | null
  slug: string | null
  store: {
    title: string | null
    slug: string | null
    previewImageUrl: string | null
    gid: string | null
    status: string | null
    priceRange: {
      minVariantPrice: number | null
      maxVariantPrice: number | null
    } | null
  } | null
}>
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    _type,    title,    "slug": slug.current,      seo {    metaTitle,    metaDescription,    metaImage  },  }
export type PAGE_QUERYResult = {
  _id: string
  _type: 'page'
  title: string | null
  slug: string | null
  seo: {
    metaTitle: string | null
    metaDescription: string | null
    metaImage: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
} | null
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{      seo {    metaTitle,    metaDescription,    metaImage  },    companyName,    header {      logo,      mainMenu,      headerButtons    },    footer {      logo,      logoCaption,      footerMenu,      newsletter {        newsletter {          title,          description,          klaviyoListId        },        footerButtons,        footerText,      }    },    socialMedia {      facebook,      instagram,      twitter,      linkedin    }  }
export type SITE_SETTINGS_QUERYResult = {
  seo: null
  companyName: string | null
  header: {
    logo: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    mainMenu: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'menu'
    } | null
    headerButtons: Array<{
      text?: string
      url?: string
      internalPage?:
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'blogPost'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'event'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'page'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            [internalGroqTypeReferenceTo]?: 'product'
          }
      style?: 'ghost' | 'primary' | 'secondary' | 'text'
      size?: 'default' | 'large' | 'small'
      _key: string
    }> | null
  } | null
  footer: {
    logo: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    logoCaption: string | null
    footerMenu: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'menu'
    } | null
    newsletter: {
      newsletter: null
      footerButtons: null
      footerText: null
    } | null
  } | null
  socialMedia: {
    facebook: string | null
    instagram: string | null
    twitter: string | null
    linkedin: string | null
  } | null
} | null
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)] {    "slug": slug.current  }
export type PAGE_SLUGS_QUERYResult = Array<{
  slug: string | null
}>
// Variable: PRODUCT_SLUGS_QUERY
// Query: *[_type == "product" && defined(store.slug.current)] {    "slug": store.slug.current  }
export type PRODUCT_SLUGS_QUERYResult = Array<{
  slug: string | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type == "home"][0]{\n    _id,\n    _type,\n    overview,\n    showcaseProjects[]{\n      _key,\n      ...@->{\n        _id,\n        _type,\n        coverImage,\n        overview,\n        "slug": slug.current,\n        tags,\n        title,\n      }\n    },\n    title,\n  }\n': HOME_PAGE_QUERYResult
    '\n  *[_type == "product"] {\n    _id,\n    _type,\n    title,\n    images[]{ \n  asset->{\n    _id,\n    _type,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height\n      },\n      palette {\n        dominant {\n          background,\n          foreground,\n          population,\n          title\n        }\n      }\n    }\n  },\n  hotspot {\n    x,\n    y,\n    height,\n    width\n  },\n  crop {\n    top,\n    bottom,\n    left,\n    right\n  },\n  alt,\n  priority,\n  caption,\n  _type,\n  aspectRatio,\n  objectFit\n },\n    "slug": store.slug.current,\n    store{\n      title,\n      "slug": slug.current,\n      previewImageUrl,\n      gid,\n      status,\n      priceRange{\n        minVariantPrice,\n        maxVariantPrice\n      }\n    },\n  }\n': ALL_PRODUCTS_QUERYResult
    '\n  *[_type == "page" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaImage\n  }\n,\n  }': PAGE_QUERYResult
    '\n  *[_type == "siteSettings"][0]{\n    \n  seo {\n    metaTitle,\n    metaDescription,\n    metaImage\n  }\n,\n    companyName,\n    header {\n      logo,\n      mainMenu,\n      headerButtons\n    },\n    footer {\n      logo,\n      logoCaption,\n      footerMenu,\n      newsletter {\n        newsletter {\n          title,\n          description,\n          klaviyoListId\n        },\n        footerButtons,\n        footerText,\n      }\n    },\n    socialMedia {\n      facebook,\n      instagram,\n      twitter,\n      linkedin\n    }\n  }\n': SITE_SETTINGS_QUERYResult
    '\n  *[_type == "page" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': PAGE_SLUGS_QUERYResult
    '\n  *[_type == "product" && defined(store.slug.current)] {\n    "slug": store.slug.current\n  }\n': PRODUCT_SLUGS_QUERYResult
  }
}
